[package]
name = "arm-simulator"
version = "0.1.0"
edition = "2021"

[lib]
name = "arm_simulator"
crate-type = ["lib", "cdylib"]

[dependencies]
wasm-bindgen = "0.2.85"
js-sys = "0.3.63"

[dev-dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }