[package]
name = "arm-simulator"
version = "0.2.0"
edition = "2021"

[lib]
name = "arm_simulator"
crate-type = ["lib", "cdylib"]

[dependencies]
wasm-bindgen = "0.2.90"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"

